@startuml DomainModel

package チャンク集約 {
    object チャンク {
        チャンクグリッド座標
        包含するブロックのリスト
    }

    object ブロック_チャンク {
        ブロックタイプID
        親からの相対座標
    }

    チャンク o-- "0..n" ブロック_チャンク
}

package マシンユニット集約 {
    object コアブロック {
        包含するブロックのリスト
    }

    object ブロック_MU {
        ブロックタイプID
        親からの相対座標
    }

    コアブロック o-- "0..n" ブロック_MU
}


@enduml