@startuml

object アイテム {
    ピッケル
    コンクリート
}

object ピッケル {
    耐久値
    採掘速度
}

together  {
    object コンクリート {
        形状
    }

    object 形状 {
        Cube
        Half
        Stair
        Slope
        Slope_Angle
    }
    
    コンクリート --> 色
    コンクリート --> 形状

    object 土 {

    }
}

アイテム --> ピッケル
アイテム --> コンクリート
アイテム --> 土



@enduml