@startuml DomainModel

package チャンク集約 {
    object チャンク {
        チャンクグリッド座標
        包含するブロックのリスト
    }

    object ブロック_チャンク {
        ブロックタイプID
        接面情報
    }

    チャンク o-- "0..n" ブロック_チャンク
}

package マシンユニット集約 {
    object コアブロック {
        包含するブロックのリスト
    }

    object ブロック_MU {
        ブロックタイプID
        接面情報
    }

    コアブロック o-- "0..n" ブロック_MU
}

package プレイヤー集約 {
    object Player {

    }
}


@enduml