@startuml DomainModel

package Chunk {
    object Chunk {
        ChunkGridCoordinate
    }

    object Block {
        BlockTypeID
    }

    Chunk *-- "16*16*16" Block
}

package {
    object Chunk
}

@enduml